namespace Tum4ik.JustClipboardManager.Icons;
public enum SvgIconType
{
  [SvgIconResource("caret-down")] CaretDown,
  [SvgIconResource("caret-left")] CaretLeft,
  [SvgIconResource("caret-right")] CaretRight,
  [SvgIconResource("caret-up")] CaretUp,
  [SvgIconResource("check")] Check,
  [SvgIconResource("chevron")] Chevron,
  [SvgIconResource("chrome-close")] ChromeClose,
  [SvgIconResource("chrome-maximize")] ChromeMaximize,
  [SvgIconResource("chrome-minimize")] ChromeMinimize,
  [SvgIconResource("chrome-restore")] ChromeRestore,
  [SvgIconResource("dark-mode")] DarkMode,
  [SvgIconResource("delete")] Delete,
  [SvgIconResource("display-settings")] DisplaySettings,
  [SvgIconResource("edit")] Edit,
  [SvgIconResource("expand-arrow")] ExpandArrow,
  [SvgIconResource("file")] File,
  [SvgIconResource("files")] Files,
  [SvgIconResource("info")] Info,
  [SvgIconResource("keyboard")] Keyboard,
  [SvgIconResource("light-mode")] LightMode,
  [SvgIconResource("scroll-left-arrow")] ScrollLeftArrow,
  [SvgIconResource("scroll-right-arrow")] ScrollRightArrow,
  [SvgIconResource("search")] Search,
  [SvgIconResource("settings")] Settings,
  [SvgIconResource("ukraine")] Ukraine,
  [SvgIconResource("usa")] USA
}
