//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tum4ik.JustClipboardManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class InternalSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static InternalSettings defaultInstance = ((InternalSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new InternalSettings())));
        
        public static InternalSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsSettingsUpgradeRequired {
            get {
                return ((bool)(this["IsSettingsUpgradeRequired"]));
            }
            set {
                this["IsSettingsUpgradeRequired"] = value;
            }
        }
    }
}
