//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tum4ik.JustClipboardManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class SettingsGeneral : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsGeneral defaultInstance = ((SettingsGeneral)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsGeneral())));
        
        public static SettingsGeneral Default {
            get {
                return defaultInstance;
            }
        }
    }
}
