//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tum4ik.JustClipboardManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class SettingsPasteWindow : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsPasteWindow defaultInstance = ((SettingsPasteWindow)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsPasteWindow())));
        
        public static SettingsPasteWindow Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SnappingType {
            get {
                return ((int)(this["SnappingType"]));
            }
            set {
                this["SnappingType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DisplayCorner {
            get {
                return ((int)(this["DisplayCorner"]));
            }
            set {
                this["DisplayCorner"] = value;
            }
        }
    }
}
