namespace Tum4ik.JustClipboardManager.Services.PInvoke.ParameterModels;

#pragma warning disable S101 // Types should be named in PascalCase
#pragma warning disable IDE1006 // Naming Styles

/// <summary>
/// Contains information about a simulated message generated by an input device other than a keyboard or mouse.
/// </summary>
internal struct HARDWAREINPUT
{
  /// <summary>
  /// The message generated by the input hardware.
  /// </summary>
  public uint uMsg;

  /// <summary>
  /// The low-order word of the lParam parameter for <see cref="uMsg"/>.
  /// </summary>
  public ushort wParamL;

  /// <summary>
  /// The high-order word of the lParam parameter for <see cref="uMsg"/>.
  /// </summary>
  public ushort wParamH;
}
