namespace Tum4ik.JustClipboardManager.Services.PInvoke.ParameterModels;
internal enum OBJID : uint
{
  WINDOW = 0x00000000,
  SYSMENU = 0xFFFFFFFF,
  TITLEBAR = 0xFFFFFFFE,
  MENU = 0xFFFFFFFD,
  CLIENT = 0xFFFFFFFC,
  VSCROLL = 0xFFFFFFFB,
  HSCROLL = 0xFFFFFFFA,
  SIZEGRIP = 0xFFFFFFF9,
  CARET = 0xFFFFFFF8,
  CURSOR = 0xFFFFFFF7,
  ALERT = 0xFFFFFFF6,
  SOUND = 0xFFFFFFF5
}
