//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tum4ik.JustClipboardManager.Resources.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tum4ik.JustClipboardManager.Resources.Translations.Translation", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask a question.
        /// </summary>
        internal static string AskQuestion {
            get {
                return ResourceManager.GetString("AskQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-start application.
        /// </summary>
        internal static string AutoStartApplication {
            get {
                return ResourceManager.GetString("AutoStartApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like the corresponding file with plugins info is corrupted or has wrong format. Please try again later..
        /// </summary>
        internal static string AvailablePluginsInfoLoadProblem_Body {
            get {
                return ResourceManager.GetString("AvailablePluginsInfoLoadProblem_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins info loading failed.
        /// </summary>
        internal static string AvailablePluginsInfoLoadProblem_Title {
            get {
                return ResourceManager.GetString("AvailablePluginsInfoLoadProblem_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        internal static string by {
            get {
                return ResourceManager.GetString("by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact me directly.
        /// </summary>
        internal static string ContactMeDirectly {
            get {
                return ResourceManager.GetString("ContactMeDirectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy email to clipboard.
        /// </summary>
        internal static string CopyEmailToClipboard {
            get {
                return ResourceManager.GetString("CopyEmailToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2022-2023 Yevheniy Tymchishin. All rights reserved..
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        internal static string Development {
            get {
                return ResourceManager.GetString("Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disallowed hotkey.
        /// </summary>
        internal static string DisallowedHotkey {
            get {
                return ResourceManager.GetString("DisallowedHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit hotkey.
        /// </summary>
        internal static string EditHotkey {
            get {
                return ResourceManager.GetString("EditHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hotkey is already registered.
        /// </summary>
        internal static string HotkeyIsAlreadyRegistered {
            get {
                return ResourceManager.GetString("HotkeyIsAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkeys.
        /// </summary>
        internal static string Hotkeys {
            get {
                return ResourceManager.GetString("Hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        internal static string Installed {
            get {
                return ResourceManager.GetString("Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface.
        /// </summary>
        internal static string Interface {
            get {
                return ResourceManager.GetString("Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave a feedback.
        /// </summary>
        internal static string LeaveFeedback {
            get {
                return ResourceManager.GetString("LeaveFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin download problem.
        /// </summary>
        internal static string PluginDownloadProblem_Title {
            get {
                return ResourceManager.GetString("PluginDownloadProblem_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In some reason the plugin installation failed..
        /// </summary>
        internal static string PluginInstallationProblem_Body {
            get {
                return ResourceManager.GetString("PluginInstallationProblem_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin installation problem.
        /// </summary>
        internal static string PluginInstallationProblem_Title {
            get {
                return ResourceManager.GetString("PluginInstallationProblem_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        internal static string Plugins {
            get {
                return ResourceManager.GetString("Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin installation is blocked because of security reasons..
        /// </summary>
        internal static string PluginSecurityViolation_Body {
            get {
                return ResourceManager.GetString("PluginSecurityViolation_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin security violation.
        /// </summary>
        internal static string PluginSecurityViolation_Title {
            get {
                return ResourceManager.GetString("PluginSecurityViolation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the hotkey.
        /// </summary>
        internal static string PressHotkey {
            get {
                return ResourceManager.GetString("PressHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a problem.
        /// </summary>
        internal static string ReportProblem {
            get {
                return ResourceManager.GetString("ReportProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        internal static string Sequence {
            get {
                return ResourceManager.GetString("Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like there is a problem connecting to the server. It can be caused by either internet connection problem or an error on the server side..
        /// </summary>
        internal static string ServerConnectionProblem_Body {
            get {
                return ResourceManager.GetString("ServerConnectionProblem_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server connection problem.
        /// </summary>
        internal static string ServerConnectionProblem_Title {
            get {
                return ResourceManager.GetString("ServerConnectionProblem_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show paste window.
        /// </summary>
        internal static string ShowPasteWindow {
            get {
                return ResourceManager.GetString("ShowPasteWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source code.
        /// </summary>
        internal static string SourceCode {
            get {
                return ResourceManager.GetString("SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggest an idea.
        /// </summary>
        internal static string SuggestIdea {
            get {
                return ResourceManager.GetString("SuggestIdea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some hotkeys are not defined for the application. Please, go to &quot;Settings &gt; Hotkeys&quot; to solve the problem..
        /// </summary>
        internal static string UndefinedHotkeysDetectedDescription {
            get {
                return ResourceManager.GetString("UndefinedHotkeysDetectedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined hotkeys detected.
        /// </summary>
        internal static string UndefinedHotkeysDetectedTitle {
            get {
                return ResourceManager.GetString("UndefinedHotkeysDetectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        internal static string Uninstall {
            get {
                return ResourceManager.GetString("Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
