// <auto-generated />
using System;
using JustClipboardManager.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JustClipboardManager.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("JustClipboardManager.Domain.Entities.Clip", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ClippedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now', 'localtime')");

                    b.Property<byte[]>("PreviewData")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("SearchLabel")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SearchLabel");

                    b.ToTable("Clips", t =>
                        {
                            t.HasComment("Represents a single item in the clipboard history.");
                        });
                });

            modelBuilder.Entity("JustClipboardManager.Domain.Entities.ClipDataObject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ClipId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("FormatId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClipId");

                    b.ToTable("ClipDataObjects", t =>
                        {
                            t.HasComment("Contains a clipboard item data for a specific format.");
                        });
                });

            modelBuilder.Entity("JustClipboardManager.Domain.Entities.ClipDataObject", b =>
                {
                    b.HasOne("JustClipboardManager.Domain.Entities.Clip", null)
                        .WithMany("ClipDataObjects")
                        .HasForeignKey("ClipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JustClipboardManager.Domain.Entities.Clip", b =>
                {
                    b.Navigation("ClipDataObjects");
                });
#pragma warning restore 612, 618
        }
    }
}
