using Tum4ik.JustClipboardManager.PluginDevKit.Attributes;

namespace Tum4ik.JustClipboardManager.Resources.Icons;
public enum SvgIconType
{
  [SvgIconResource("bug-report")] BugReport,
  [SvgIconResource("cancel-circle-filled")] CancelCircleFilled,
  [SvgIconResource("caret-down")] CaretDown,
  [SvgIconResource("caret-left")] CaretLeft,
  [SvgIconResource("caret-right")] CaretRight,
  [SvgIconResource("caret-up")] CaretUp,
  [SvgIconResource("check")] Check,
  [SvgIconResource("check-circle")] CheckCircle,
  [SvgIconResource("check-circle-filled")] CheckCircleFilled,
  [SvgIconResource("chevron")] Chevron,
  [SvgIconResource("chrome-close")] ChromeClose,
  [SvgIconResource("chrome-maximize")] ChromeMaximize,
  [SvgIconResource("chrome-minimize")] ChromeMinimize,
  [SvgIconResource("chrome-restore")] ChromeRestore,
  [SvgIconResource("code")] Code,
  [SvgIconResource("copy-content")] CopyContent,
  [SvgIconResource("dark-mode")] DarkMode,
  [SvgIconResource("delete")] Delete,
  [SvgIconResource("display-settings")] DisplaySettings,
  [SvgIconResource("edit")] Edit,
  [SvgIconResource("email-alternate")] EmailAlternate,
  [SvgIconResource("expand-arrow")] ExpandArrow,
  [SvgIconResource("extension")] Extension,
  [SvgIconResource("fact-check")] FactCheck,
  [SvgIconResource("feedback")] Feedback,
  [SvgIconResource("file")] File,
  [SvgIconResource("files")] Files,
  [SvgIconResource("format-list-numbered-rtl")] FormatListNumberedRtl,
  [SvgIconResource("info")] Info,
  [SvgIconResource("info-filled")] InfoFilled,
  [SvgIconResource("keyboard")] Keyboard,
  [SvgIconResource("lightbulb")] Lightbulb,
  [SvgIconResource("light-mode")] LightMode,
  [SvgIconResource("live-help")] LiveHelp,
  [SvgIconResource("manage-search")] ManageSearch,
  [SvgIconResource("scroll-left-arrow")] ScrollLeftArrow,
  [SvgIconResource("scroll-right-arrow")] ScrollRightArrow,
  [SvgIconResource("search")] Search,
  [SvgIconResource("settings")] Settings,
  [SvgIconResource("ukraine")] Ukraine,
  [SvgIconResource("usa")] USA,
  [SvgIconResource("warning-circle-filled")] WarningCircleFilled
}
