name: Codecov

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  update-coverage:
    name: Update coverage
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Setup VSTest.console.exe
      uses: darenm/Setup-VSTest@v1.2

    - name: Test
      run: |
        msbuild /t:Restore /t:Build /p:Configuration=Release
        vstest.console.exe .\Tests\*.UnitTests\bin\Release\*\*.UnitTests.dll `
          /Parallel `
          /Enablecodecoverage `
          /Collect:"Code Coverage;Format=Cobertura"

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
