name: Gated (Application)

on:
  workflow_dispatch:
  push:
    branches:
      - 'release/**'
  pull_request:
    branches:
      - 'main'
      - 'release/**'
    paths-ignore:
      - '.attachments/**'
      - '.editorconfig'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

jobs:

  build:
    strategy:
      matrix:
        platform:
          - id: windows-latest
            name: Windows
            runtime-identifier: win-x64
          - id: ubuntu-latest
            name: Ubuntu
            runtime-identifier: linux-x64

    name: Gated Build (${{ matrix.platform.name }})
    runs-on: ${{ matrix.platform.id }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Clean Install
      run: npm ci

    - name: Electron Forge make
      shell: pwsh
      run: |
        dotnet publish ./dotnet/JustClipboardManager.ClipboardListener/JustClipboardManager.ClipboardListener.csproj `
          -c Release `
          -r ${{ matrix.platform.runtime-identifier }} `
          --self-contained `
          --output ./dist/dotnet `
          --nologo `
          /p:Version=4.0.0
        npm run prod-electron-forge-make

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: BuildFiles_${{ matrix.platform.name }}
        path: |
          out/make
