name: Gated (Application)

on:
  workflow_dispatch:
  push:
    branches:
      - 'release/**'
  pull_request:
    branches:
      - 'main'
      - 'release/**'
    paths-ignore:
      - '.attachments/**'
      - '.editorconfig'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

jobs:

  build:
    strategy:
      matrix:
        platform:
          - id: windows-latest
            name: Windows
          - id: ubuntu-latest
            name: Ubuntu

    name: Gated Build (${{ matrix.platform.name }})
    runs-on: ${{ matrix.platform.id }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'

    - name: Clean Install
      run: npm ci

    - name: Electron Forge make
      run: npm run electron-forge-make

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: BuildFiles_${{ matrix.platform.name }}
        path: |
          out/make
